debug = true
logLevel = "DEBUG"

[Log]
  filePath = "/tmp/traefik.log"
  format   = "json"

[accessLog]
  filePath = "/tmp/access.log"
  format = "json"

#defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.traefik]
  address = ":8080"
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":8888"

[tcp]
  [tcp.routers.to-ssl-helloworld]
    rule = "HostSNI(`*`)"
    service = "ssl-helloworld"
      [tcp.routers.to-ssl-helloworld.tls]
        passthrough = true 

[api]
  entryPoint = "traefik"
  dashboard = true

[web]
address = ":8080"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "demo.local"
watch = true
exposedByDefault = false

#rules
